version: "3.9"

services:
  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: streamify-db
    ports:
      - "3308:3306"
    networks:
      - streamify-net
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: streamify-backend
    ports:
      - "8086:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/streamify-db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy
    networks:
      - streamify-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: streamify-frontend
    ports:
      - "8085:8080"
    depends_on:
      - backend
    networks:
      - streamify-net

volumes:
  db-data:

networks:
  streamify-net:
    driver: bridge
